### ISSUE TITLE
cp: can't stat 'usher_lineage_report.csv': No such file or directory error during assembly

### ISSUE THREAD

**Issue by nityendra21** [alvesrco/covid19_itvds#4]
Hi, I'm experiencing the error given below during the assembly process 
```
Using UShER as inference engine.
****
Pangolin running in usher mode.
****
Maximum ambiguity allowed is 0.3.
****
Query file:	/output/home/thermite/setu_test/pipecov/11-pangolin_lineages/../test1_closedgap.fasta
****
Data files found:
usher_pb:	/opt/conda/envs/pangolin/lib/python3.10/site-packages/pangolin_data/data/lineageTree.pb
****
****
Output file written to: /output/home/thermite/setu_test/pipecov/11-pangolin_lineages/lineage_report.csv
****
Output alignment written to: /output/home/thermite/setu_test/pipecov/11-pangolin_lineages/alignment.fasta
cp: can't stat 'usher_lineage_report.csv': No such file or directory
```
Any help is greatly appreciated!

**Comment by reinator** [comment]
Hi @nityendra21!
Thanks for providing this feedback.

I believe that the pangolin result was generated without any problem. The file "lineage_report.csv" will have the Usher analysis to identify the variant.

Anyway, I have just updated the code for assembly_docker.sh, now specifying the results for both Usher and Pangolearn analysis mode. If you could run the analysis again and test it, please.

If you face any other problems, just let us know! 
Cheers!

**Comment by nityendra21** [comment]
Now the issue that I'm facing is that the pipeline runs without any problem but no output files are generated in the folder that I provided with the -o flag.

**Comment by nityendra21** [comment]
Okay, I've found the output files in the pipecov/pipes/Mapping_Assembly folder. Thanks for the help!
